if (RET)
    message(WARNING "Cannot determine current revision. Make sure that you are building either from a Git working tree or from a source archive.")
    configure_file("${CMAKE_CURRENT_SOURCE_DIR}/src/config/version.h.in" "${TO}")
else ()
    configure_file("${CMAKE_CURRENT_SOURCE_DIR}/src/config/version.h.in" "${TO}")
endif ()
